name: Mineunit runner
description: "Execute unit tests with mineunit, busted & luacov"
author: SX / S-S-X
branding:
  icon: file-text
  color: green

inputs:
  working-directory:
    description: "Working directory for unit tests"
    required: true
    default: "."
  mineunit-args:
    description: "Additional arguments for mineunit"
    required: false
  badge-name:
    description: "Code coverage badge name"
    required: true
    default: "coverage"
  badge-label:
    description: "Code coverage badge label"
    required: true
    default: "Test coverage"
  badge-color:
    description: "Code coverage badge color"
    required: true
    default: "99CC09"
  mineunit-version:
    description: "Mineunit version"
    required: false

outputs:
  # Generated or supplied badge properties
  badge-name:
    description: "Code coverage badge name waiting for issues/#1"
  badge-label:
    description: "Code coverage badge label waiting for issues/#1"
  badge-status:
    description: "Code coverage badge status waiting for issues/#1"
  badge-color:
    description: "Code coverage badge color waiting for issues/#1"

  # Mineunit test framework output
  mineunit-stdout:
    description: "Stdout produced during busted run"
  mineunit-spec-missing:
    description: "Set to true if no spec files found for busted"

  mineunit-report:
    description: "Mineunit detailed test report"

  coverage-total:
    description: "Total test coverage percentage"
  coverage-files:
    description: "Number of files tested and total number of source files"

  # Help content / on demand documentation
  help-busted-spec-missing:
    description: "Help for situation where spec files could not be loaded"
    value: |
      #### It seems your project is missing spec files, you should add some spec files to spec directory.
      If you already have spec directory with `*_spec.lua` files then problem is probably `working-directory` settings.
      `working-directory` should point to directory where `spec` directory is located.
      
      Example when you have tests in `/src/mystuff/spec` directory:
      ```
      - uses: mt-mods/mineunit-actions@master
        with:
          working-directory: ./src/mystuff
      ```

runs:
  using: docker
  image: Dockerfile
